using TwinCAT.Ads;

namespace PlcGateway.Drivers.Beckhoff
{
    public static class AdsErrorCodeExtensions
    {
        public static string ToMessage(this TwinCAT.Ads.AdsErrorCode errorCode)
        {
            return errorCode switch
            {
                // Global Errors
                TwinCAT.Ads.AdsErrorCode.NoError => "No error - The ADS request succeeded.",
                TwinCAT.Ads.AdsErrorCode.InternalError => "Internal Error - This error is very generic and there is no further information available about the problem.",
                TwinCAT.Ads.AdsErrorCode.NoRTime => "No Realtime available.",
                TwinCAT.Ads.AdsErrorCode.LockedMemoryError => "Allocation locked memory error.",
                TwinCAT.Ads.AdsErrorCode.MailBoxError => "Mailbox error - The Mailbox is full. Reduce the number of ADS messages per cycle.",
                TwinCAT.Ads.AdsErrorCode.WrongHMsg => "Wrong receive HMSG.",
                TwinCAT.Ads.AdsErrorCode.TargetPortNotFound => "Target port not found - The ADS server is not started or is not reachable.",
                TwinCAT.Ads.AdsErrorCode.TargetMachineNotFound => "Target machine not found - The Target computer / AMS route was not found. Check the AMS route.",
                TwinCAT.Ads.AdsErrorCode.UnknownCommandID => "Unknown command ID.",
                TwinCAT.Ads.AdsErrorCode.BadTaskID => "Bad task ID.",
                TwinCAT.Ads.AdsErrorCode.NoIO => "No IO.",
                TwinCAT.Ads.AdsErrorCode.UnknownAmsCommand => "Unknown AMS command.",
                TwinCAT.Ads.AdsErrorCode.Win32Error => "Win32 error.",
                TwinCAT.Ads.AdsErrorCode.PortNotConnected => "Port is not connected.",
                TwinCAT.Ads.AdsErrorCode.InvalidAmsLength => "Invalid AMS length.",
                TwinCAT.Ads.AdsErrorCode.InvalidAmsNetID => "Invalid AMS Net ID.",
                TwinCAT.Ads.AdsErrorCode.LowInstallLevel => "Low installation level - TwinCAT 2 license error.",
                TwinCAT.Ads.AdsErrorCode.NoDebug => "No debug available.",
                TwinCAT.Ads.AdsErrorCode.PortDisabled => "Port disabled - The TwinCAT system service is not in an active state (config, running).",
                TwinCAT.Ads.AdsErrorCode.PortConnected => "Port is already connected.",
                TwinCAT.Ads.AdsErrorCode.AmsSyncWin32Error => "AMS Sync Win32 error.",
                TwinCAT.Ads.AdsErrorCode.SyncTimeOut => "AMS Sync timeout.",
                TwinCAT.Ads.AdsErrorCode.AmsSyncAmsError => "AMS Sync AMS error.",
                TwinCAT.Ads.AdsErrorCode.AmsSyncNoIndexMap => "No index map for AMS Sync available.",
                TwinCAT.Ads.AdsErrorCode.InvalidAmsPort => "Invalid AMS port.",
                TwinCAT.Ads.AdsErrorCode.NoMemory => "No memory.",
                TwinCAT.Ads.AdsErrorCode.TCPSendError => "TCP send error.",
                TwinCAT.Ads.AdsErrorCode.HostUnreachable => "Host is unreachable.",
                TwinCAT.Ads.AdsErrorCode.AmsInvalidFragment => "Invalid AMS fragment.",
                TwinCAT.Ads.AdsErrorCode.TlsSendError => "TLS send error - secure ADS connection failed.",
                TwinCAT.Ads.AdsErrorCode.AccessDenied => "Access denied - secure ADS access denied.",
                TwinCAT.Ads.AdsErrorCode.TcpConnectionRefused => "TCP Connection refused.",

                // Router Errors
                TwinCAT.Ads.AdsErrorCode.NoLockedMemory => "Router: No locked memory - Locked memory cannot be allocated.",
                TwinCAT.Ads.AdsErrorCode.ResizeMemory => "Router: The size of the router memory could not be changed.",
                TwinCAT.Ads.AdsErrorCode.MailboxFull => "Router: Mailbox full - The mailbox has reached the maximum number of possible messages.",
                TwinCAT.Ads.AdsErrorCode.DebugBoxFull => "Router: Debug mailbox full.",
                TwinCAT.Ads.AdsErrorCode.UnknownPortType => "Router: Unknown Port Type.",
                TwinCAT.Ads.AdsErrorCode.RouterNotInitialized => "Router: Router is not initialized.",
                TwinCAT.Ads.AdsErrorCode.PortAlreadyInUse => "Router: The desired port number is already assigned.",
                TwinCAT.Ads.AdsErrorCode.PortNotRegistered => "Router: Port not registered.",
                TwinCAT.Ads.AdsErrorCode.NoMoreQueues => "Router: The maximum number of Ports reached.",
                TwinCAT.Ads.AdsErrorCode.InvalidPort => "Router: The port is invalid.",
                TwinCAT.Ads.AdsErrorCode.RouterNotActive => "Router: TwinCAT Router not active.",
                TwinCAT.Ads.AdsErrorCode.RouterFragmentBoxFull => "Router: The mailbox has reached the maximum number for fragmented messages.",
                TwinCAT.Ads.AdsErrorCode.RouterFragmentTimeout => "Router: A fragment timeout has occurred.",
                TwinCAT.Ads.AdsErrorCode.RouterPortToBeRemoved => "Router: The port is removed.",

                // Device Errors
                TwinCAT.Ads.AdsErrorCode.DeviceError => "Device Error.",
                TwinCAT.Ads.AdsErrorCode.DeviceServiceNotSupported => "Device: The requested Service is not supported by the server.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidGroup => "Device: Invalid index group.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidOffset => "Device: Invalid index offset.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidAccess => "Device: Reading/writing not permitted.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidSize => "Device: Parameter size not correct.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidData => "Device: Invalid parameter value(s).",
                TwinCAT.Ads.AdsErrorCode.DeviceNotReady => "Device: Device is not in a ready state.",
                TwinCAT.Ads.AdsErrorCode.DeviceBusy => "Device: Device is busy. Try the request later.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidContext => "Device: Invalid context (must be in Windows).",
                TwinCAT.Ads.AdsErrorCode.DeviceNoMemory => "Device: The device ran out of memory.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidParam => "Device: Invalid parameter value(s).",
                TwinCAT.Ads.AdsErrorCode.DeviceNotFound => "Device: Not found (files, ...).",
                TwinCAT.Ads.AdsErrorCode.DeviceSyntaxError => "Device: Syntax error in command or file.",
                TwinCAT.Ads.AdsErrorCode.DeviceIncompatible => "Device: Objects do not match.",
                TwinCAT.Ads.AdsErrorCode.DeviceExists => "Device: Object already exists on device.",
                TwinCAT.Ads.AdsErrorCode.DeviceSymbolNotFound => "Device: Symbol not found on the device/target.",
                TwinCAT.Ads.AdsErrorCode.DeviceSymbolVersionInvalid => "Device: Symbol version is invalid. Variable handle may be invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidState => "Device: Server is not in a valid state.",
                TwinCAT.Ads.AdsErrorCode.DeviceTransModeNotSupported => "Device: ADS transmode is not supported.",
                TwinCAT.Ads.AdsErrorCode.DeviceNotifyHandleInvalid => "Device: Notification handle is invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceClientUnknown => "Device: Notification client not registered.",
                TwinCAT.Ads.AdsErrorCode.DeviceNoMoreHandles => "Device: No more notification handles.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidWatchsize => "Device: Size for watch too big.",
                TwinCAT.Ads.AdsErrorCode.DeviceNotInitialized => "Device: Device is not initialized.",
                TwinCAT.Ads.AdsErrorCode.DeviceTimeOut => "Device: Device has a timeout.",
                TwinCAT.Ads.AdsErrorCode.DeviceNoInterface => "Device: Query interface has failed.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidInterface => "Device: Wrong interface required.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidCLSID => "Device: Class ID is invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidObjectID => "Device: Object ID is invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceRequestIsPending => "Device: A Request is Pending. Try later to access the request result.",
                TwinCAT.Ads.AdsErrorCode.DeviceRequestIsAborted => "Device: Request is Aborted.",
                TwinCAT.Ads.AdsErrorCode.DeviceSignalWarning => "Device: Signal warning.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidArrayIndex => "Device: Invalid Array Index.",
                TwinCAT.Ads.AdsErrorCode.DeviceSymbolNotActive => "Device: Symbol not Active.",
                TwinCAT.Ads.AdsErrorCode.DeviceAccessDenied => "Device: Access denied.",
                TwinCAT.Ads.AdsErrorCode.DeviceLicenseNotFound => "Device: License not found.",
                TwinCAT.Ads.AdsErrorCode.DeviceLicenseExpired => "Device: License expired.",
                TwinCAT.Ads.AdsErrorCode.DeviceLicenseExceeded => "Device: License exceeded.",
                TwinCAT.Ads.AdsErrorCode.DeviceLicenseInvalid => "Device: License invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceException => "Device: Exception in device specific code.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidFunctionId => "Device: Function ID is invalid.",
                TwinCAT.Ads.AdsErrorCode.DeviceOutOfRange => "Device: A parameter, an index, an iterator, ... is out of range.",
                TwinCAT.Ads.AdsErrorCode.DeviceInvalidAlignment => "Device: Invalid alignment.",

                // Client Errors
                TwinCAT.Ads.AdsErrorCode.ClientError => "Client Error.",
                TwinCAT.Ads.AdsErrorCode.ClientInvalidParameter => "Client: Parameter at service is invalid.",
                TwinCAT.Ads.AdsErrorCode.ClientListEmpty => "Client: Polling list is empty.",
                TwinCAT.Ads.AdsErrorCode.ClientVariableInUse => "Client: Variable connection is already in use.",
                TwinCAT.Ads.AdsErrorCode.ClientDuplicateInvokeID => "Client: Invoke ID already in use.",
                TwinCAT.Ads.AdsErrorCode.ClientSyncTimeOut => "Client: Timeout has elapsed.",
                TwinCAT.Ads.AdsErrorCode.ClientW32Error => "Client: Error in win32 subsystem.",
                TwinCAT.Ads.AdsErrorCode.ClientTimeoutInvalid => "Client: Timeout value is invalid.",
                TwinCAT.Ads.AdsErrorCode.ClientPortNotOpen => "Client: ADS port is not opened.",
                TwinCAT.Ads.AdsErrorCode.ClientNoAmsAddr => "Client: No AMS Address.",
                TwinCAT.Ads.AdsErrorCode.ClientSyncInternal => "Client: An internal in ADS sync has occurred.",
                TwinCAT.Ads.AdsErrorCode.ClientResponseInvalid => "Client: An invalid response has been received.",
                TwinCAT.Ads.AdsErrorCode.ClientPortLocked => "Client: The synchronous ADS Port is locked.",
                TwinCAT.Ads.AdsErrorCode.ClientRequestCancelled => "Client: The client Request was cancelled (asynchronously).",
                TwinCAT.Ads.AdsErrorCode.ClientQueueFull => "Client: The ADS Client queue is full.",

                // Windows Socket Errors
                TwinCAT.Ads.AdsErrorCode.WSA_ConnAborted => "Windows Socket: Software caused connection abort.",
                TwinCAT.Ads.AdsErrorCode.WSA_ConnReset => "Windows Socket: Connection reset by peer.",
                TwinCAT.Ads.AdsErrorCode.WSA_ConnRefused => "Windows Socket: Connection refused.",
                TwinCAT.Ads.AdsErrorCode.WSA_TimedOut => "Windows Socket: Connection attempt timed out.",
                TwinCAT.Ads.AdsErrorCode.WSA_HostUnreachable => "Windows Socket: No route to the specified host.",

                _ => $"Unknown ADS error code: {errorCode} (0x{(uint)errorCode:X8})"
            };
        }
    }
}
