using TwinCAT.Ads;

namespace PlcGateway.Drivers.Beckhoff
{
    public static class AdsErrorCodeExtensions
    {
        public static string ToMessage(this AdsErrorCode errorCode)
        {
            return errorCode switch
            {
                // Global Errors
                AdsErrorCode.NoError => "No error - The ADS request succeeded.",
                AdsErrorCode.InternalError => "Internal Error - This error is very generic and there is no further information available about the problem.",
                AdsErrorCode.NoRTime => "No Realtime available.",
                AdsErrorCode.LockedMemoryError => "Allocation locked memory error.",
                AdsErrorCode.MailBoxError => "Mailbox error - The Mailbox is full. Reduce the number of ADS messages per cycle.",
                AdsErrorCode.WrongHMsg => "Wrong receive HMSG.",
                AdsErrorCode.TargetPortNotFound => "Target port not found - The ADS server is not started or is not reachable.",
                AdsErrorCode.TargetMachineNotFound => "Target machine not found - The Target computer / AMS route was not found. Check the AMS route.",
                AdsErrorCode.UnknownCommandID => "Unknown command ID.",
                AdsErrorCode.BadTaskID => "Bad task ID.",
                AdsErrorCode.NoIO => "No IO.",
                AdsErrorCode.UnknownAmsCommand => "Unknown AMS command.",
                AdsErrorCode.Win32Error => "Win32 error.",
                AdsErrorCode.PortNotConnected => "Port is not connected.",
                AdsErrorCode.InvalidAmsLength => "Invalid AMS length.",
                AdsErrorCode.InvalidAmsNetID => "Invalid AMS Net ID.",
                AdsErrorCode.LowInstallLevel => "Low installation level - TwinCAT 2 license error.",
                AdsErrorCode.NoDebug => "No debug available.",
                AdsErrorCode.PortDisabled => "Port disabled - The TwinCAT system service is not in an active state (config, running).",
                AdsErrorCode.PortConnected => "Port is already connected.",
                AdsErrorCode.AmsSyncWin32Error => "AMS Sync Win32 error.",
                AdsErrorCode.SyncTimeOut => "AMS Sync timeout.",
                AdsErrorCode.AmsSyncAmsError => "AMS Sync AMS error.",
                AdsErrorCode.AmsSyncNoIndexMap => "No index map for AMS Sync available.",
                AdsErrorCode.InvalidAmsPort => "Invalid AMS port.",
                AdsErrorCode.NoMemory => "No memory.",
                AdsErrorCode.TCPSendError => "TCP send error.",
                AdsErrorCode.HostUnreachable => "Host is unreachable.",
                AdsErrorCode.AmsInvalidFragment => "Invalid AMS fragment.",
                AdsErrorCode.TlsSendError => "TLS send error - secure ADS connection failed.",
                AdsErrorCode.AccessDenied => "Access denied - secure ADS access denied.",
                AdsErrorCode.TcpConnectionRefused => "TCP Connection refused.",

                // Router Errors
                AdsErrorCode.NoLockedMemory => "Router: No locked memory - Locked memory cannot be allocated.",
                AdsErrorCode.ResizeMemory => "Router: The size of the router memory could not be changed.",
                AdsErrorCode.MailboxFull => "Router: Mailbox full - The mailbox has reached the maximum number of possible messages.",
                AdsErrorCode.DebugBoxFull => "Router: Debug mailbox full.",
                AdsErrorCode.UnknownPortType => "Router: Unknown Port Type.",
                AdsErrorCode.RouterNotInitialized => "Router: Router is not initialized.",
                AdsErrorCode.PortAlreadyInUse => "Router: The desired port number is already assigned.",
                AdsErrorCode.PortNotRegistered => "Router: Port not registered.",
                AdsErrorCode.NoMoreQueues => "Router: The maximum number of Ports reached.",
                AdsErrorCode.InvalidPort => "Router: The port is invalid.",
                AdsErrorCode.RouterNotActive => "Router: TwinCAT Router not active.",
                AdsErrorCode.RouterFragmentBoxFull => "Router: The mailbox has reached the maximum number for fragmented messages.",
                AdsErrorCode.RouterFragmentTimeout => "Router: A fragment timeout has occurred.",
                AdsErrorCode.RouterPortToBeRemoved => "Router: The port is removed.",

                // Device Errors
                AdsErrorCode.DeviceError => "Device Error.",
                AdsErrorCode.DeviceServiceNotSupported => "Device: The requested Service is not supported by the server.",
                AdsErrorCode.DeviceInvalidGroup => "Device: Invalid index group.",
                AdsErrorCode.DeviceInvalidOffset => "Device: Invalid index offset.",
                AdsErrorCode.DeviceInvalidAccess => "Device: Reading/writing not permitted.",
                AdsErrorCode.DeviceInvalidSize => "Device: Parameter size not correct.",
                AdsErrorCode.DeviceInvalidData => "Device: Invalid parameter value(s).",
                AdsErrorCode.DeviceNotReady => "Device: Device is not in a ready state.",
                AdsErrorCode.DeviceBusy => "Device: Device is busy. Try the request later.",
                AdsErrorCode.DeviceInvalidContext => "Device: Invalid context (must be in Windows).",
                AdsErrorCode.DeviceNoMemory => "Device: The device ran out of memory.",
                AdsErrorCode.DeviceInvalidParam => "Device: Invalid parameter value(s).",
                AdsErrorCode.DeviceNotFound => "Device: Not found (files, ...).",
                AdsErrorCode.DeviceSyntaxError => "Device: Syntax error in command or file.",
                AdsErrorCode.DeviceIncompatible => "Device: Objects do not match.",
                AdsErrorCode.DeviceExists => "Device: Object already exists on device.",
                AdsErrorCode.DeviceSymbolNotFound => "Device: Symbol not found on the device/target.",
                AdsErrorCode.DeviceSymbolVersionInvalid => "Device: Symbol version is invalid. Variable handle may be invalid.",
                AdsErrorCode.DeviceInvalidState => "Device: Server is not in a valid state.",
                AdsErrorCode.DeviceTransModeNotSupported => "Device: ADS transmode is not supported.",
                AdsErrorCode.DeviceNotifyHandleInvalid => "Device: Notification handle is invalid.",
                AdsErrorCode.DeviceClientUnknown => "Device: Notification client not registered.",
                AdsErrorCode.DeviceNoMoreHandles => "Device: No more notification handles.",
                AdsErrorCode.DeviceInvalidWatchsize => "Device: Size for watch too big.",
                AdsErrorCode.DeviceNotInitialized => "Device: Device is not initialized.",
                AdsErrorCode.DeviceTimeOut => "Device: Device has a timeout.",
                AdsErrorCode.DeviceNoInterface => "Device: Query interface has failed.",
                AdsErrorCode.DeviceInvalidInterface => "Device: Wrong interface required.",
                AdsErrorCode.DeviceInvalidCLSID => "Device: Class ID is invalid.",
                AdsErrorCode.DeviceInvalidObjectID => "Device: Object ID is invalid.",
                AdsErrorCode.DeviceRequestIsPending => "Device: A Request is Pending. Try later to access the request result.",
                AdsErrorCode.DeviceRequestIsAborted => "Device: Request is Aborted.",
                AdsErrorCode.DeviceSignalWarning => "Device: Signal warning.",
                AdsErrorCode.DeviceInvalidArrayIndex => "Device: Invalid Array Index.",
                AdsErrorCode.DeviceSymbolNotActive => "Device: Symbol not Active.",
                AdsErrorCode.DeviceAccessDenied => "Device: Access denied.",
                AdsErrorCode.DeviceLicenseNotFound => "Device: License not found.",
                AdsErrorCode.DeviceLicenseExpired => "Device: License expired.",
                AdsErrorCode.DeviceLicenseExceeded => "Device: License exceeded.",
                AdsErrorCode.DeviceLicenseInvalid => "Device: License invalid.",
                AdsErrorCode.DeviceException => "Device: Exception in device specific code.",
                AdsErrorCode.DeviceInvalidFunctionId => "Device: Function ID is invalid.",
                AdsErrorCode.DeviceOutOfRange => "Device: A parameter, an index, an iterator, ... is out of range.",
                AdsErrorCode.DeviceInvalidAlignment => "Device: Invalid alignment.",

                // Client Errors
                AdsErrorCode.ClientError => "Client Error.",
                AdsErrorCode.ClientInvalidParameter => "Client: Parameter at service is invalid.",
                AdsErrorCode.ClientListEmpty => "Client: Polling list is empty.",
                AdsErrorCode.ClientVariableInUse => "Client: Variable connection is already in use.",
                AdsErrorCode.ClientDuplicateInvokeID => "Client: Invoke ID already in use.",
                AdsErrorCode.ClientSyncTimeOut => "Client: Timeout has elapsed.",
                AdsErrorCode.ClientW32Error => "Client: Error in win32 subsystem.",
                AdsErrorCode.ClientTimeoutInvalid => "Client: Timeout value is invalid.",
                AdsErrorCode.ClientPortNotOpen => "Client: ADS port is not opened.",
                AdsErrorCode.ClientNoAmsAddr => "Client: No AMS Address.",
                AdsErrorCode.ClientSyncInternal => "Client: An internal in ADS sync has occurred.",
                AdsErrorCode.ClientResponseInvalid => "Client: An invalid response has been received.",
                AdsErrorCode.ClientPortLocked => "Client: The synchronous ADS Port is locked.",
                AdsErrorCode.ClientRequestCancelled => "Client: The client Request was cancelled (asynchronously).",
                AdsErrorCode.ClientQueueFull => "Client: The ADS Client queue is full.",

                // Windows Socket Errors
                AdsErrorCode.WSA_ConnAborted => "Windows Socket: Software caused connection abort.",
                AdsErrorCode.WSA_ConnReset => "Windows Socket: Connection reset by peer.",
                AdsErrorCode.WSA_ConnRefused => "Windows Socket: Connection refused.",
                AdsErrorCode.WSA_TimedOut => "Windows Socket: Connection attempt timed out.",
                AdsErrorCode.WSA_HostUnreachable => "Windows Socket: No route to the specified host.",

                _ => $"Unknown ADS error code: {errorCode} (0x{(uint)errorCode:X8})"
            };
        }
    }
}
